### ISSUE TITLE
`Parser Error: Identifiers not found: screensize`

### ISSUE THREAD

**Issue by ghost** [kidscancode/Godot3_dodge#8]
```
extends Area2D

export (int) var speed #how fast the player will move

func _ready():
		screensize = get_viewport_rect().size

func _process(delta):
	var velocity = vector2() #player's movement vector
	if Input.action_pressed("ui_right"):
		velocity.x += 1
	if Input.actio_pressed("ui_left"):
		velocity.x -= 1
	if Input.is_action_pressed("ui_down"):
        velocity.y += 1
	if Input.is_action_pressed("ui_up"):
		velocity.y -= 1
	if velocity.length() > 0:
		velocity = velocity.normalized() * speed
		$AnimatedSprite.play()
	else:
		$AnimatedSprite.stop()
		
	position += velocity * delta
	position.x = clamp(position.x, 0, screensize.x)
	position.y = clamp(position.y, 0, screensize.y)

```
This is the code from the tutorial. When I tried to run it. It throws error:
`Parser Error: Identifiers not found: screensize`

Please help

**Comment by Strongground** [comment]
Try replacing 
`screensize = get_viewport_rect().size`
with 
`var screensize = get_viewport_rect().size`

**Comment by ghost** [comment]
@Strongground Tried it. Same received error.

**Comment by cbscribe** [comment]
"Identifier not found" happens when you try and use a variable you haven't declared with `var`. Your error is because you never declared the `screensize` variable. At the top (before `_ready()`) you need to declare the variable:

`var screensize`

Location matters. If you put `var screensize` in `_ready()` then it becomes a local variable, and only exists in that function, giving you an error when you try to use it in `_process()`. By declaring it outside the function scope, it becomes available to all functions in the script.
